<a href="https://colab.research.google.com/github/Youssef-S-Ahmed/Credit-Card-Fraud-Detection/blob/main/credit_card_fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data preprocessing Tools

# 1.Importing Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

#machine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_absolute_percentage_error

# 2.importing Dataset.

In [ ]:
dataset = pd.read_csv("creditcard.csv")
df = pd.DataFrame(dataset)
df

Time        V1        V2        V3        V4        V5        V6  \
0         0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1         0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2         1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3         1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4         2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
...     ...       ...       ...       ...       ...       ...       ...   
9960  14837  1.286884 -0.124610  0.148283 -0.259343  0.248357  0.896718   
9961  14854  1.318742  0.496408  0.114876  0.695262  0.170133 -0.537180   
9962  14857  1.241757  0.419587  0.806183  0.894811 -0.507886 -1.118126   
9963  14861  1.304800 -0.052885  0.415235 -0.081725 -0.223525  0.097752   
9964  14864 -1.747939  3.712444       NaN       NaN       NaN       NaN   

            V7        V8        V9  ...       V21       V22       V23  \
0     0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474   
1    -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288   
2     0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412   
3     0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321   
4     0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458   
...        ...       ...       ...  ...       ...       ...       ...   
9960 -0.626627  0.227693  1.618678  ... -0.381864 -0.904515 -0.027985   
9961  0.025492 -0.272931  1.267298  ... -0.484943 -1.111176  0.028259   
9962  0.018908 -0.343335  1.210781  ... -0.379396 -0.817785  0.181425   
9963 -0.561240  0.067228  1.617203  ... -0.379597 -0.929204  0.020955   
9964       NaN       NaN       NaN  ...       NaN       NaN       NaN   

           V24       V25       V26       V27       V28  Amount  Class  
0     0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62    0.0  
1    -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69    0.0  
2    -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66    0.0  
3    -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50    0.0  
4     0.141267 -0.206010  0.502292  0.219422  0.215153   69.99    0.0  
...        ...       ...       ...       ...       ...     ...    ...  
9960 -1.743540  0.090885  0.870425 -0.084116 -0.022744   12.18    0.0  
9961 -0.549934  0.328634  0.106061 -0.046154  0.017304    1.78    0.0  
9962  0.662879  0.172535  0.033636 -0.051084  0.017208    1.29    0.0  
9963 -0.877006  0.084384  0.807465 -0.099851 -0.015404    4.72    0.0  
9964       NaN       NaN       NaN       NaN       NaN     NaN    NaN  

[9965 rows x 31 columns]

In [ ]:
combined_df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [ ]:
# Count NaN values in each column
nan_counts = df.isna().sum()
nan_counts

Time      0
V1        0
V2        0
V3        1
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
#dealing with rest col with Object dtype
df = df.dropna()

In [ ]:
df.describe()

Time           V1           V2           V3           V4  \
count   9964.000000  9964.000000  9964.000000  9964.000000  9964.000000   
mean    5933.588719    -0.241530     0.280348     0.906359     0.260247   
std     4448.730907     1.522697     1.308496     1.156948     1.440500   
min        0.000000   -27.670569   -34.607649   -15.496222    -4.657545   
25%     2061.000000    -1.011783    -0.208614     0.412198    -0.615591   
50%     4546.000000    -0.372609     0.286168     0.943149     0.218492   
75%    10162.250000     1.151550     0.900736     1.601871     1.119367   
max    14861.000000     1.960497     8.636214     4.101716    10.463020   

                V5           V6           V7           V8           V9  ...  \
count  9964.000000  9964.000000  9964.000000  9964.000000  9964.000000  ...   
mean     -0.046342     0.132335    -0.071847    -0.065317     0.801220  ...   
std       1.183634     1.307586     1.077872     1.260140     1.156424  ...   
min     -32.092129   -23.496714   -26.548144   -23.632502    -6.329801  ...   
25%      -0.643060    -0.630075    -0.542336    -0.190495     0.069439  ...   
50%      -0.153090    -0.153577    -0.054658     0.012466     0.804930  ...   
75%       0.371762     0.503376     0.476280     0.273016     1.506066  ...   
max      34.099309    21.393069    34.303177     5.060381    10.392889  ...   

               V21          V22          V23          V24          V25  \
count  9964.000000  9964.000000  9964.000000  9964.000000  9964.000000   
mean     -0.052099    -0.152091    -0.033426     0.021638     0.087302   
std       0.914735     0.631310     0.488203     0.593818     0.428128   
min     -11.468435    -8.527145   -15.144340    -2.512377    -2.577363   
25%      -0.268191    -0.548412    -0.174222    -0.327438    -0.157704   
50%      -0.123101    -0.136078    -0.046009     0.079935     0.121180   
75%       0.032707     0.247913     0.081288     0.410877     0.359418   
max      22.588989     4.534454    13.876221     3.200201     5.525093   

               V26          V27          V28       Amount        Class  
count  9964.000000  9964.000000  9964.000000  9964.000000  9964.000000  
mean      0.108328     0.005614     0.003051    62.968359     0.003814  
std       0.562661     0.411434     0.266532   184.626707     0.061641  
min      -1.338556    -7.976100    -3.509250     0.000000     0.000000  
25%      -0.328193    -0.084489    -0.015751     5.000000     0.000000  
50%       0.043395    -0.004505     0.015904    15.950000     0.000000  
75%       0.478249     0.121045     0.077418    50.792500     0.000000  
max       3.517346     8.254376     4.860769  7712.430000     1.000000  

[8 rows x 31 columns]

In [ ]:
# Check the dataset shape
print(df.shape)
print(df['Class'].value_counts())

(9964, 31)
Class
0.0    9926
1.0      38
Name: count, dtype: int64


In [ ]:
df['Class'].unique()

array([0., 1.])

In [ ]:
df

Time        V1        V2        V3        V4        V5        V6  \
0         0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1         0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2         1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3         1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4         2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
...     ...       ...       ...       ...       ...       ...       ...   
9959  14834  1.180311 -0.268826  1.373170 -0.623739 -1.237326 -0.495057   
9960  14837  1.286884 -0.124610  0.148283 -0.259343  0.248357  0.896718   
9961  14854  1.318742  0.496408  0.114876  0.695262  0.170133 -0.537180   
9962  14857  1.241757  0.419587  0.806183  0.894811 -0.507886 -1.118126   
9963  14861  1.304800 -0.052885  0.415235 -0.081725 -0.223525  0.097752   

            V7        V8        V9  ...       V21       V22       V23  \
0     0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474   
1    -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288   
2     0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412   
3     0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321   
4     0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458   
...        ...       ...       ...  ...       ...       ...       ...   
9959 -0.909022 -0.000706  2.961146  ...  0.170907  0.974244 -0.036893   
9960 -0.626627  0.227693  1.618678  ... -0.381864 -0.904515 -0.027985   
9961  0.025492 -0.272931  1.267298  ... -0.484943 -1.111176  0.028259   
9962  0.018908 -0.343335  1.210781  ... -0.379396 -0.817785  0.181425   
9963 -0.561240  0.067228  1.617203  ... -0.379597 -0.929204  0.020955   

           V24       V25       V26       V27       V28  Amount  Class  
0     0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62    0.0  
1    -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69    0.0  
2    -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66    0.0  
3    -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50    0.0  
4     0.141267 -0.206010  0.502292  0.219422  0.215153   69.99    0.0  
...        ...       ...       ...       ...       ...     ...    ...  
9959  0.383235  0.369188 -0.581899  0.098968  0.035401    2.00    0.0  
9960 -1.743540  0.090885  0.870425 -0.084116 -0.022744   12.18    0.0  
9961 -0.549934  0.328634  0.106061 -0.046154  0.017304    1.78    0.0  
9962  0.662879  0.172535  0.033636 -0.051084  0.017208    1.29    0.0  
9963 -0.877006  0.084384  0.807465 -0.099851 -0.015404    4.72    0.0  

[9964 rows x 31 columns]

In [ ]:
x = df.iloc[: , :-1].values
y = df.iloc[: , -1].values

In [ ]:
print (x) # x contains the features or the independent variables
print("--------------------------")
print(y) # y contains the dependent variables or the predicted that we want the model to be able to predict

[[ 0.00000000e+00 -1.35980713e+00 -7.27811733e-02 ...  1.33558377e-01
  -2.10530535e-02  1.49620000e+02]
 [ 0.00000000e+00  1.19185711e+00  2.66150712e-01 ... -8.98309914e-03
   1.47241692e-02  2.69000000e+00]
 [ 1.00000000e+00 -1.35835406e+00 -1.34016307e+00 ... -5.53527940e-02
  -5.97518406e-02  3.78660000e+02]
 ...
 [ 1.48540000e+04  1.31874232e+00  4.96407864e-01 ... -4.61543712e-02
   1.73042790e-02  1.78000000e+00]
 [ 1.48570000e+04  1.24175672e+00  4.19586742e-01 ... -5.10838932e-02
   1.72077499e-02  1.29000000e+00]
 [ 1.48610000e+04  1.30480050e+00 -5.28847393e-02 ... -9.98514999e-02
  -1.54037053e-02  4.72000000e+00]]
--------------------------
[0. 0. 0. ... 0. 0. 0.]


In [ ]:
print(x.shape)
print(y.shape)

(9964, 30)
(9964,)


# Splitting the Dataset into Training set & Test set

In [ ]:
# creating instance
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size = 0.6 , random_state = 1)

print(x_train)
print("-----------------------")
print(y_train)
print("-----------------------")
print(x_test)
print("-----------------------")
print(y_test)

[[ 4.19200000e+03  1.06411656e+00 -1.02075105e+00 ... -4.80916357e-02
   3.32391116e-02  1.25900000e+02]
 [ 3.15700000e+03 -1.28371842e-01  9.57775425e-01 ...  2.33248522e-01
   2.32709693e-01  1.84000000e+01]
 [ 1.33230000e+04 -5.45436178e+00  8.28742056e+00 ...  1.57471478e+00
   8.08725205e-01  1.00000000e+00]
 ...
 [ 6.81000000e+02  1.12087185e+00  1.42425238e-01 ...  5.75305839e-02
   2.33089305e-02  9.99000000e+00]
 [ 4.95600000e+03  1.30077372e+00  1.65218226e-01 ... -4.98938742e-02
   1.84456980e-02  8.99000000e+00]
 [ 1.56000000e+02 -3.49486086e+00 -2.89444973e+00 ...  3.09675191e-01
   6.32260841e-01  5.00000000e+02]]
-----------------------
[0. 0. 1. ... 0. 0. 0.]
-----------------------
[[ 1.08390000e+04 -1.39716933e+00  1.27907156e+00 ...  2.47241015e-01
   1.81637354e-01  2.50000000e+01]
 [ 9.74400000e+03  1.19794207e+00  2.52099278e-03 ... -8.36097052e-02
   4.65361642e-03  1.37100000e+01]
 [ 7.63000000e+02  1.48149506e+00 -2.67244460e-01 ... -2.64791021e-02
  -1.8609975

#SVM(Kernel'rbf')

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = "rbf" , random_state=0)
classifier.fit(x_train, y_train)

SVC(random_state=0)

In [ ]:
y_pred = classifier.predict(x_test)
print(y_pred)

[0. 0. 0. ... 0. 0. 0.]


In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[5963    0]
 [  16    0]]
0.9973239672185984


#SVM(Kernel'Linear')

In [ ]:
classifier_2 = SVC(kernel = "linear" , random_state=0)
classifier_2.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
y_pred_2 = classifier.predict(x_test)
print(y_pred_2)

[0. 0. 0. ... 0. 0. 0.]


In [ ]:
cm_2 = confusion_matrix(y_test,y_pred_2)
print(cm_2)
print(accuracy_score(y_test,y_pred_2))

[[5963    0]
 [  16    0]]
0.9973239672185984


#Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier


c = RandomForestClassifier(n_estimators=10 , criterion="entropy", random_state=0)
c.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
y_p_3 = c.predict(x_train)

cmm = confusion_matrix(y_train,y_p_3)
print(cmm)
print(accuracy_score(y_train,y_p_3))

[[3963    0]
 [   0   22]]
1.0


In [ ]:
y_pred_3 = c.predict(x_test)

cm_3 = confusion_matrix(y_test,y_pred_3)
print(cm_3)
print(accuracy_score(y_test,y_pred_3))

[[5963    0]
 [   2   14]]
0.9996654959023248
